
def actividad_simple(titulo, tipo, precio, fechahora, duracion, url):
    salida = '<div class="row">'
    salida += '<div class="12u">'
    salida += '<section>'
    salida += '<header>'
    salida += '<h2>' + titulo + '</h2>'
    salida += '<span class="byline">' + tipo + '</span>'
    salida += '</header>'
    salida += '<p>' + precio + '</p>'
    salida += '<p>' + fechahora + '</p>'
    salida += '<p>' + duracion + '</p>'
    salida += '<a href="' + url + '" class="button">Mas info</a>'
    salida += '</section>'
    salida += '</div></div>'
    return salida
    
def actividad_completa(titulo, tipo, precio, fechahora, duracion, url, localizacion, lugar, distrito, masinfo):
    salida = '<div class="row">'
    salida += '<div class="12u">'
    salida += '<section>'
    salida += '<header>'
    salida += '<h2>' + titulo + '</h2>'
    salida += '<span class="byline">' + tipo + '</span>'
    salida += '</header>'
    salida += '<p>' + precio + '</p>'
    salida += '<p>' + fechahora + '</p>'
    salida += '<p>' + duracion + '</p>'
    salida += '<p id="localizacion">' + localizacion + '</p>'
    salida += '<p>' + lugar + '</p>'
    salida += '<p>' + distrito + '</p>'
    salida += '<p>' + masinfo + '</p>'
    salida += '<a href="' + url + '" class="button">ENLACE</a>'
    salida += '</section>'
    salida += '</div></div>'
    return salida
    
def formulario_login():
    salida = '<form action="login" method="post" id="login-form">'
    salida += '<div class="form-row">'
    salida += '<label for="id_username" class="required">Username:</label> <input id="id_username" maxlength="254" name="username" type="text" />'
    salida += '</div>'
    salida += '<div class="form-row">'
    salida += '<label for="id_password" class="required">Password:</label> <input id="id_password" name="password" type="password" />'
    salida += '</div>'
    salida += '<div class="submit-row">'
    salida += '<label>&nbsp;</label><input type="submit" value="Log in" />'
    salida += '</div>'
    salida += '</form>'
    return salida
    
def formularios_cambio(recurso):
    salida = '<div class="form-row">'
    salida += '<form action="' + recurso + '" method="post">'
    salida += '<label for="id_titulo" class="required">Titulo:</label> <input id="id_titulo" name="titulo" type="text" />'
    salida += '<button class="button">Cambiar</button>'
    salida += '</form>'
    salida += '<form action="' + recurso + '" method="post">'
    salida += '<label for="id_descripcion" class="required">Descripcion:</label> <input id="id_descripcion" name="descripcion" type="text" />'
    salida += '<button class="button">Cambiar</button>'
    salida += '</form>'
    salida += '<form action="' + recurso + '" method="post">'
    salida += '<hr>'
    salida += '<label for="id_colorletra" class="required">Color de la letra:</label> <input id="id_colorletra" name="colorletra" type="text" />'
    salida += '<label for="id_imagenfondo" class="required">Imagen de fondo:</label> <input id="id_imagenfondo" name="imagenfondo" type="text" />'
    salida += '<label for="id_colortitulotop" class="required">Gradiente titulo (arriba):</label> <input id="id_colortitulotop" name="colortitulotop" type="text" /><br>'
    salida += '<label for="id_colortitulobot" class="required">Gradiente titulo (abajo):</label> <input id="id_colortitulobot" name="colortitulobot" type="text" />'
    salida += '<label for="id_colorbordetitulo" class="required">Color borde del titulo:</label> <input id="id_colorbordetitulo" name="colorbordetitulo" type="text" />'
    salida += '<label for="id_colornavbar" class="required">Color Navbar</label> <input id="id_colornavbar" name="colornavbar" type="text" /><br>'   
    salida += '<button class="button">Cambiar CSS</button>'
    salida += '</form>'
    salida += '<form action="" method="post"><button class="button" name="reset" value="reset">Reset CSS</button></form>'
    salida += '</div><hr>'
    return salida    

